### ISSUE TITLE
Licensing? I want to use the statemachine script :P

### ISSUE THREAD

**Issue by loolo78** [fafase/unity-utilities#1]
Came from Gems, but since it's in GitHub it'll still be nice to have a license for the script.

**Comment by fafase** [comment]
The licensing is the same as on gems, I will copy it onto github but the idea is that you can use it in any project, commercial or not as long as the project is not the script itself. So you cannot just copy the fsm and sell it as fsm asset with little changes here and there but you can build and sell your game using the fsm without any modification. Let me know if that is clear enough.

**Comment by loolo78** [comment]
Thank you!

**Comment by loolo78** [comment]
I translated the StateMachine to a custom language my school uses called Zilch. I want to share it with my classmates. Is that ok with you?

Here's a secre gist to the source code: https://gist.github.com/loolo78/d07a74e31063f26772c5

**Comment by fafase** [comment]
It is fine. Since you are translating line for line, you can share and use it but please do not sell the fsm as it is even in a different language. That is all I ask. I will add a mention on translation in the licensing.

**Comment by loolo78** [comment]
Thank you! And thank you so much for unity gems, really really high quality articles that helps the entire community :)
